### ISSUE TITLE
Android todo app doesn't sync and crashes when pressing subscription button

### ISSUE THREAD

**Issue by ArikonUA** [mongodb-university/realm-template-apps#193]
Hello, I was following tutorial for Kotlin todo app, but having some major issues.
I run the app on hardware device. On login screen, I pressed 'create new account', after providing details and registering, screen goes black. In logcat I see that registration and login were successful, but there an ANR. (I tried the same on the emulator, it also resulted in ANR).
After this I reopen the app, luckily I'm already signed in. I can see todo app UI. I've added several items. Next, as tutorial suggests, I go to Atlas website to 'browse collections' - it's empty. In the android app, if I press button with wifi icon (I assume it's sync?), the app instantly crashes with:

> Process: com.mongodb.app, PID: 17568
                                                                                                    java.lang.NullPointerException
                                                                                                    	at io.realm.kotlin.mongodb.internal.SubscriptionSetImpl.waitForSynchronization-VtjQ1oo(SubscriptionSetImpl.kt:126)
                                                                                                    	at io.realm.kotlin.mongodb.internal.SubscriptionSetImpl$waitForSynchronization$1.invokeSuspend(Unknown Source:16)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8177)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@4954412, Dispatchers.Main]

On the website, in App Services section I can see some activity - there is 1 user and some requests. My app id in atlasConfig.xml seems to be correct

**Comment by dacharyc** [comment]
Hey @ArikonUA  - I'm sorry you're having problems. Thanks for letting us know. I don't have a hardware device to test with, and was unable to replicate these issues on an emulator. I'll have to forward the information to our engineering team to have them look into this for us.

Can you let us know what hardware device you're using?

**Comment by dacharyc** [comment]
Hey @ArikonUA - it looks like the Sync-related issues may be due to an issue when creating a template app. That issue may have been resolved with an internal release yesterday. If you create a new template app, hopefully everything will work. Or if you still have problems, creating a new App Services App without a template, and then configuring things manually, would be another possible workaround.

Let me know if this resolves your issue!

**Comment by dacharyc** [comment]
Just following up - it looks like another developer ran into a similar issue in #191 , and this resolved their issue. I'm going to assume you've hit the same issue, and the same fix or workaround will resolve your problem. I'll go ahead and close this issue, but if you still have a problem after applying these suggestions, feel free to re-open with more details.
