### ISSUE TITLE
react-native template from realm does not initiate correctly with xcode 69.5

### ISSUE THREAD

**Issue by Paco-Mateu** [mongodb-university/realm-template-apps#91]
The app is correctly built, but when it is initiated, appears the next error on the simulator:

```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Error: Unable to resolve module ./index from /Users/user1/apps/learning-fm/MyRealmApp/.: <br><br>None of these files exist:<br> &nbsp;* index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)<br> &nbsp;* index/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)<br> &nbsp; &nbsp;at ModuleResolver.resolveDependency (/Users/user1/apps/learning-fm/MyRealmApp/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:136:15)<br> &nbsp; &nbsp;at DependencyGraph.resolveDependency (/Users/user1/apps/learning-fm/MyRealmApp/node_modules/metro/src/node-haste/DependencyGraph.js:231:43)<br> &nbsp; &nbsp;at /Users/user1/apps/learning-fm/MyRealmApp/node_modules/metro/src/lib/transformHelpers.js:129:24<br> &nbsp; &nbsp;at Server._resolveRelativePath (/Users/user1/apps/learning-fm/MyRealmApp/node_modules/metro/src/Server.js:1137:12)<br> &nbsp; &nbsp;at async Server.requestProcessor [as _processBundleRequest] (/Users/user1/apps/learning-fm/MyRealmApp/node_modules/metro/src/Server.js:464:37)<br> &nbsp; &nbsp;at async Server._processRequest (/Users/user1/apps/learning-fm/MyRealmApp/node_modules/metro/src/Server.js:420:9)</pre>
</body>
</html>


RCTFatal
__28-[RCTCxxBridge handleError:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_drain
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
-[UIApplication _run]
UIApplicationMain
main
start_sim
0x0

```

I execute the npx react-native init command from the app main folder, the one which contains app.json, realm.json, ios and android folders, etc...

What am I supposed to do different?

Thank a lot in advance!

<img width="1015" alt="Screenshot 2022-08-27 at 16 18 41" src="https://user-images.githubusercontent.com/66885250/187034242-2d35cc96-a3bc-4193-9232-91e0a06b844a.png">

**Comment by Paco-Mateu** [comment]
Solved: using xcode builder instead of react-native-cli.

**Comment by cbush** [comment]
Thanks!
